language: python
python:
  - 2.6
  - 2.7
#  - 3.2
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
before_install: easy_install -U infi.projector
install: projector devenv build
# command to run tests, e.g. python setup.py test
script: bin/nosetests
